select * FROM DOLGOZO;
SELECT * FROM DOLGOZO WHERE FIZETES > 2800;
SELECT * FROM DOLGOZO WHERE (
    OAZON = 10 OR 
    OAZON = 20
);

SELECT * FROM DOLGOZO WHERE JUTALEK > 600;
SELECT * FROM DOLGOZO WHERE JUTALEK <= 600;
SELECT DISTINCT FOGLALKOZAS FROM DOLGOZO WHERE FOGLALKOZAS IS NOT null;
SELECT FIZETES * 2 FROM DOLGOZO WHERE OAZON = 10;
SELECT DNEV, BELEPES FROM DOLGOZO WHERE BELEPES > '1982.01.01';
SELECT DNEV FROM DOLGOZO WHERE FONOKE IS null;
SELECT DNEV FROM DOLGOZO WHERE DNEV LIKE '%A%';
SELECT DNEV FROM DOLGOZO WHERE DNEV LIKE '%L%L%';
SELECT DNEV FROM DOLGOZO WHERE (
    FIZETES > 2000
    AND
    FIZETES < 3000
);

SELECT * FROM DOLGOZO ORDER BY FIZETES;
SELECT * FROM DOLGOZO ORDER BY FIZETES DESC, DNEV ASC;
SELECT DNEV FROM DOLGOZO WHERE FONOKE = (SELECT DKOD FROM DOLGOZO WHERE DNEV = 'KING');
SELECT DNEV FROM DOLGOZO WHERE FONOKE = (SELECT DKOD FROM DOLGOZO WHERE FOGLALKOZAS != 'MANAGER');